name: Main

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/synocommunity/spksrc
    name: Release
    steps:
      - name: Pull synocommunity
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'SynoCommunity'
          repository: 'spksrc'
          
      - name: Prepare build
        run: cd spksrc/ && make setup

      - name: Get latest cloudflared version string
        id: cloudflared-version
        run: |
          echo "VERSION=$(git -c 'versionsort.suffix=-' \
          ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/cloudflare/cloudflared.git '*.*.*' \
          | tail --lines=1 \
          | cut --delimiter='/' --fields=3)" >> $GITHUB_OUTPUT
          
      - name: Update cloudflared version
        run: | 
          sed -i "s/^PKG_VERS = [0-9]\+\.[0-9]\+\.[0-9]\+/PKG_VERS = ${steps.cloudflared-version.outputs.VERSION}/" cross/cloudflared/Makefile && \
          sed -i -E "
          s/^SPK_VERS = [0-9]+\.[0-9]+\.[0-9]+/SPK_VERS = ${steps.cloudflared-version.outputs.VERSION}/;
          s/^SPK_REV = [0-9]+/SPK_REV = & + 1/e
          " filename

      
      - name: Build all-supported
        run: cd spksrc/spk/cloudflared && make all-supported
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: /spksrc/packages/
          
  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages
          
      - name: Calculate sha256
        run: |
          {
            echo 'SUMS<<EOF'
            find . -type f -exec sha256sum {} \;
            echo EOF
          } >> "$GITHUB_OUTPUT"
        id: sha256

      - name: Print sha256
        run: echo '${{ steps.sha256.outputs.SUMS }}'

      - name: Get latest cloudflared version string
        id: cloudflared-version
        run: |
          echo "VERSION=$(git -c 'versionsort.suffix=-' \
          ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/cloudflare/cloudflared.git '*.*.*' \
          | tail --lines=1 \
          | cut --delimiter='/' --fields=3)" >> $GITHUB_OUTPUT
          
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cloudflared*
          tag: ${{ steps.cloudflared-version.outputs.VERSION }}
          overwrite: true
          body: ${{ steps.sha256.outputs.SUMS }}
          file_glob: true
